export const TOKEN = 'token';
export const REFRESH_TOKEN = 'refresh_token';

export const CLEAR = 'CLEAR';

// auth
export const AUTH_START_LOGIN = `AUTH_START_LOGIN`;
export const AUTH_SUCCESS_LOGIN = `AUTH_SUCCESS_LOGIN`;
export const AUTH_FAILED_LOGIN = `AUTH_FAILED_LOGIN`;
export const LOGOUT = `LOGOUT`;


// modal
export const OPEN_MODAL = 'modals/open';
export const CLOSE_MODAL = 'modals/close';

export const MODAL_KEY_MAP = {
  CARD_DETAIL: 'CARD_DETAIL',
  CREATE_CARD: 'CREATE_CARD',
  CREATE_PHASE: 'CREATE_PHASE',
  PIPE_SETTING: 'PIPE_SETTING',
  CREATE_CONDITION: 'CREATE_CONDITION',
};

//questions
export const QUESTION_REQUEST_IN_PROGRESS = 'QUESTION_REQUEST_IN_PROGRESS';
export const QUESTION_FETCHED = 'QUESTION_FETCHED';
export const QUESTION_CREATED = 'QUESTION_CREATED';
export const QUESTION_UPDATED = 'QUESTION_UPDATED';
export const QUESTION_REQUEST_FAILURE = 'QUESTION_REQUEST_FAILURE';

//answers
export const ANSWER_REQUEST_IN_PROGRESS = 'ANSWER_REQUEST_IN_PROGRESS';
export const ANSWER_FETCHED = 'ANSWER_FETCHED';
export const ANSWER_CREATED = 'ANSWER_CREATED';
export const ANSWER_UPDATED = 'ANSWER_UPDATED';
export const ANSWER_REQUEST_FAILURE = 'ANSWER_REQUEST_FAILURE';