projectKind: "front"
envAsFile:
  enabled: false
  path: /usr/src/app/.env

command: "npm"

extraArg:
  - "run"
  - "start"

metrics:
  jmx:
    enabled: false

service:
  port: 3000

extraConfig:
  BUILD_ENV: PROD
  DOMAINNAME: kian.digital
  SITE_URL: https://reg.irancr.com
  SERVER_ADDRESS: https://api.irancr.com/onboarding/api
  FILE_SERVER_ADDRESS: https://api.kiandigital.com/glusterproxy/api
  AUTH_CLIENT_ID: onboarding-web
  AUTH_BASEURL: https://neshanid.com/auth/realms/KIAN/protocol/openid-connect

ingress:
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  hosts:
    - domain: reg.irancr.com
      defaultSubdomains: false
      tls:
        enabled: true
      paths:
        - /?(.*)